version: "3"
services: 
    web:
        build:
            context: .
            dockerfile: .docker/angular.dockerfile
        volumes: 
            - ./build:/www/
        ports:
            - 8090:80